//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class projectManagementEntities : DbContext
    {
        public projectManagementEntities()
            : base("name=projectManagementEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<APPLY_TABLE> APPLY_TABLE { get; set; }
        public DbSet<COMPLETE_TABLE> COMPLETE_TABLE { get; set; }
        public DbSet<CONFIRM_TABLE> CONFIRM_TABLE { get; set; }
        public DbSet<MEM_LOG_TABLE> MEM_LOG_TABLE { get; set; }
        public DbSet<PRO_TABLE> PRO_TABLE { get; set; }
        public DbSet<SUP_LOG_TABLE> SUP_LOG_TABLE { get; set; }
    }
}
