//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRO_TABLE
    {
        public int PID { get; set; }
        public string PNAME { get; set; }
        public string PSTATE { get; set; }
        public string PCATEGORY { get; set; }
    }
}
