app.controller("login",function($scope,$http,$location){
    $scope.login=function(){
        $http.post("https://localhost:44347/api/login",$scope.data)
        .then(function(resp){
            console.log(resp.data);
            localStorage.setItem("token",resp.data.AccessToken);
            $location.path("/UserDashboard");
        },function(err){
            console.log(err);
        });
    };
});
