//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class admin
    {
        public int a_id { get; set; }
        public string a_name { get; set; }
        public string a_email { get; set; }
        public Nullable<int> a_phone { get; set; }
        public string a_address { get; set; }
        public string a_image { get; set; }
    }
}
