//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class assignedtask
    {
        public int ass_id { get; set; }
        public int u_id { get; set; }
        public int t_id { get; set; }
        public string status { get; set; }
    
        public virtual User User { get; set; }
    }
}
