//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class assignment
    {
        public int a_id { get; set; }
        public Nullable<int> amount { get; set; }
        public string deadline { get; set; }
        public Nullable<int> tree_number { get; set; }
        public string status { get; set; }
        public int ass_id { get; set; }
        public int a_number { get; set; }
    }
}
