//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class task
    {
        public int t_id { get; set; }
        public string prove_image { get; set; }
        public string quantity { get; set; }
        public string deadline { get; set; }
        public string tree_type { get; set; }
        public string status { get; set; }
        public Nullable<int> v_id { get; set; }
    
        public virtual volunteer volunteer { get; set; }
    }
}
