//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class tree_plantation_dbEntities : DbContext
    {
        public tree_plantation_dbEntities()
            : base("name=tree_plantation_dbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<admin> admins { get; set; }
        public DbSet<assigned> assigneds { get; set; }
        public DbSet<assignedtask> assignedtasks { get; set; }
        public DbSet<assignment> assignments { get; set; }
        public DbSet<authentication> authentications { get; set; }
        public DbSet<donation> donations { get; set; }
        public DbSet<donor> donors { get; set; }
        public DbSet<request> requests { get; set; }
        public DbSet<task> tasks { get; set; }
        public DbSet<Token> Tokens { get; set; }
        public DbSet<tree> trees { get; set; }
        public DbSet<User> Users { get; set; }
        public DbSet<volunteer> volunteers { get; set; }
    }
}
