//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.assignedtasks = new HashSet<assignedtask>();
            this.Tokens = new HashSet<Token>();
        }
    
        public int Id { get; set; }
        public string u_name { get; set; }
        public Nullable<int> u_phone { get; set; }
        public string u_address { get; set; }
        public string u_image { get; set; }
        public string u_email { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
    
        public virtual ICollection<assignedtask> assignedtasks { get; set; }
        public virtual ICollection<Token> Tokens { get; set; }
    }
}
