//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class volunteer
    {
        public volunteer()
        {
            this.assigneds = new HashSet<assigned>();
            this.requests = new HashSet<request>();
            this.tasks = new HashSet<task>();
        }
    
        public int v_id { get; set; }
        public string v_name { get; set; }
        public string v_email { get; set; }
        public Nullable<int> v_phone { get; set; }
        public string v_address { get; set; }
        public string v_image { get; set; }
    
        public virtual ICollection<assigned> assigneds { get; set; }
        public virtual ICollection<request> requests { get; set; }
        public virtual ICollection<task> tasks { get; set; }
    }
}
